### ISSUE TITLE
Question: How do you generate the html?

### ISSUE THREAD

**Issue by Sebastian-Nielsen** [soulshined/ft-syntax-highlight#3]
Question: How do you generate the html? I am specifically interested in generating the html for Python.

**Comment by soulshined** [comment]
Hi @Sebastian-Nielsen I'm not entirely sure what you mean by 'generate'. This isn't an automation package, it's statically typed, meaning you have to manually type the syntax. Would you mind elaborating your question so I can at least help point you in the right direction?

**Comment by Sebastian-Nielsen** [comment]
@soulshined Basically what you just said, writing the html out manually is very time consuming and trivial. Something that could be automated: I give it e.g. a python script and it spits out the corresponding html of it, such that I can apply `ft-syntax-highlight` css to it. 

But I guess there doesn't (yet) exist such a program that generates the appropriate html for a given language?

**Comment by soulshined** [comment]
@Sebastian-Nielsen well writing it out manually is the intent of progressive enhancement design and the purpose packages like this. No worries if it's not right for you, there are other syntax highlighters out there, very credible ones, that automatically highlight an elements text; a quick google search will help you. I don't know how to help you with the generation part though, as it's still not immediately clear. For now ill close this.

**Comment by nicholaswmin** [comment]
@Sebastian-Nielsen  You need a tokenizer, a script that parses source code and splits it into meaningful syntactical structures. This is 10-15 lines with Regex

Syntax highlighting is: 

1. Tokenization
2. wrap the tokens in `<span class="identifier">` for example
3. use something like this project for theming (coloring)

**Comment by soulshined** [comment]
> @Sebastian-Nielsen You need a tokenizer, a script that parses source code and splits it into meaningful syntactical structures. This is 10-15 lines with Regex
> 

1. Never use regex for language parsing/tokenizing. It's just a good rule of thumb if you don't want to be bothered with issue requests or maintenance requests. For example, https://stackoverflow.com/a/1732454/2353523
2. There are plenty of programs/software/solutions out there that support this need, albeit javascript, rust, elixr etc. Plenty of language parsers out there that would automate this for you already so no need for me to re-invent the wheel. Not to mention, there are tons and tons of syntax highlighters out there that have tons more features than I do because there is a javascript component to theirs. Pros and cons to each.

Please keep in mind this meant to be a purely CSS solution. It's about the challenge and being progressive, not convenience. 

For me to do what's being asked, this single project will become a full time job because what is really being asked is me to create tokenizers for all the languages this library supports, vb, csharp, php, html, css etc; in addition to all the _versions_ of each language. For example python 2 vs python 3, csharp 7 vs csharp 9 would literally be a full time job and beyond the scope of what this was meant for. Now you may understand why it's not exactly a good decision for 1 person to take on in his/her free time. 

This project was created 5+ years ago, and to do something purely CSS at that time with the features and skin themes I was able to create is worth the challenge alone. Now that it's been 5 years technology has evolved and I'm totally okay and aware that this doesn't fit many development needs anymore; that's okay with me

I do plan on revisiting this project this year and modernize it and make it easier to extend, but it will maintain it's pure CSS roots. 

I fully understand the need and why people are asking but that was never the intent of this project, [as outlined in the readme](https://github.com/soulshined/ft-syntax-highlight?tab=readme-ov-file#about). But with that said, this is open source, if you want something, no one is stopping you from creating one and socializing it. 

I'd have to be sincerely and thoroughly convinced on why this project needs that and why I should spend my free time integrating that. If you could create a tokenizer with pure CSS then that sounds like something more my speed!

**Comment by nicholaswmin** [comment]
Hi soulshined, you misunderstood me. I was replying to the OP. I fully get the point of your project and I'm familiar with your other work as well. I'm a fan.

In fact I'll go as far as to say I wouldn't star this if it had a tokenizer. 

> Never use regex for language parsing/tokenizing. It's just a good rule of thumb if you don't want to be bothered with issue requests or maintenance requests.

Good tip

**Comment by soulshined** [comment]
> Hi soulshined, you misunderstood me. I was replying to the OP. I fully get the point of your project and I'm familiar with your other work as well. I'm a fan.
> 
> 
> 
> In fact I'll go as far as to say I wouldn't star this if it had a tokenizer. 
> 
> 
> 
> > Never use regex for language parsing/tokenizing. It's just a good rule of thumb if you don't want to be bothered with issue requests or maintenance requests.
> 
> 
> 
> Good tip
> 
> 

I'm so sorry. I totally did misunderstand and you even tagged them 🤦🏼‍♂️ That's on me sincerely sorry. I'll leave this up even if I look dumb though because I do get emails every now and then about this. I don't know how but it got picked up on some website at some point so I do see this question every once in a while it will be a nice quick link to send to someone as an explainer

**Comment by nicholaswmin** [comment]
I'm with you 100%, trust me I miss the tags as well and I reply much worse than you did, then I'm hardpressed to leave the comment up just for completeness. 

No worries my man plus the additional info is much appreciated because in fact i am messing with tokenizers just these past 2 weeks.

>  don't know how but it got picked up on some website at some point 

I ended up here from Richard Gabriels essay "Worse is Better", which can be taken as minimalism in software design. It's a loooong story but your work has that kind of twist in a non-literal way, esp. the html compiler, its clean and it tries to make do with the minimum denominator, just the HTML. This project is similar in philosophy. I know its Progressive Enhancement at the end of the day, but the 2-3 projects of yours ive seen seem to have it as a core philosophy.
Maybe not exactly what the essay is about but kiiindaa similar. Hard to explain. 

I got a hunch you might know what im talking about already, but just in case here it is if you're interested. 

- [Worse is Better][1]

[1]: https://en.wikipedia.org/wiki/Worse_is_better
